name: node_type_try
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dep
        run: npm install
      - name: typescript build
        run: npm run build
      - name: docker login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - name: docker build
        run: docker build -t node_type_try:latest . 
